### PR TITLE
Fix #87 wrong language detection

### LINKED ISSUE #87: Wrong language detection
In the Step1 select the Spanish language and fill the form data.
Click "Siguiente" and you will get the Step2 in english instead of spanish.

### PR DESCRIPTION
**Pull request by phproberto**
After being stored in session the language tag "es-ES" was wrongly returned as "es-es". This breaks the installation step1 remember language.

I've modified the model to force the "es-ES" format. Also ensured that language is allways loaded from the setup model. 

Also fixed the main controller to load the content in the active language. Before step2 was allways in english.

And finally I've fixed the json response lang string. Sometimes JFactory::getLanguage()->getTag(); is null. Now the  response will allways try to load the string selected by the user.

I'm sure that there is a better approach for all this fixes but I hope to point you on the right direction and save some debugging time.

### CODE REVIEW

**Comment by realityking** [comment]
Hmm, what exactly is broken by this?

The InstallationJsonResponse object is supposed to be generic beyond the installation so if possible we should avoid tying it to the model.

**Comment by phproberto** [comment]
Fixes: 

1) Installation step1 select language non-english. Go to step2. Tab content is in english.
2) Installation step1 select a language. Go to step2. Return to step1. Language selection is lost.
3) InstallationJsonResponse sometimes returns null. Fixed to return language selected by the user.

I'm going to replace the model call in InstallationJsonResponse to get the data from the user session.

**Comment by phproberto** [comment]
Just tested it again with the latest version and bugs are still there.

Other user reported the same bugs in:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=28899

**Comment by phproberto** [comment]
Done. Also kept r.lang !== null validation previously removed from installation.js because the lang string can still be null if the user doesn't select any language and clicks next.

**Comment by infograf768** [comment]
I confirm that:
1. Browser language detection now works
2. Language is not lost anymore when passing from step x back to step1
3. Language defined in localise.xml is correctly used

Looks good to me

**Comment by infograf768** [comment]
Please commit this.

**Comment by phproberto** [comment]
If you think that there is something wrong/improvable just tell me and I'll try to fix it.

Thanks!

**Comment by mbabker** [comment]
At present, this isn't automatically mergeable.  I'm doing some testing tonight, so I'll run through and see if we still need this fix and if so I'll try to manually merge it.

**Comment by phproberto** [comment]
Thanks Michael!

As I already know the issues I'll also test them again. I can also make a new pull request for the current version if you need it.

**Comment by mbabker** [comment]
You'll need a new pull request for the template9 branch.  GitHub can't change the branch a pull request is based from or to.  Otherwise, you could just push your update commits and the pull request updates itself automatically.

**Comment by phproberto** [comment]
Just tested the latest Template9 and seems to have the same issues.

I'm going to make a new pull request to template9. This way I'll recheck all the modifications again. 

Thanks Michael.

**Comment by phproberto** [comment]
Fully rechecked all and did a new template9 pull request:
https://github.com/Joomla3-Admin-template/joomla-cms/pull/116

**Pull request closed without merging**
