### PR TITLE
nav-menu icons added.

### PR DESCRIPTION
**Pull request by joom5**
I added back the icons for the nav-menu, since it looked a bit dull without them:

preview

If someone could explain me how to get back the second sub-menu level i could even make it look like on the following picture (i recently did this for another project):

preview

### CODE REVIEW

**Comment by mbabker** [comment]
Why are you using navicon-16- for the prefix?  Why can't we continue to use icon-16 as to maintain backwards compatibility?

**Comment by chalak** [comment]
Great, how about using icomoon also?
all icons in same color and compatible with other icons that used in UI.

**Comment by joom5** [comment]
You're right that 'nav' prefix is not necessary.

**Comment by mbabker** [comment]
Just for reference on the second level menus, Bootstrap doesn't support it until 2.1.  That'll be released on August 20, so we should be able to get that restored soon after (assuming migrating between Bootstrap 2.0 and 2.1 isn't a major hassle).

**Pull request closed without merging**
