### PR TITLE
Added hover action on dropdowns in admin main menu (+class nav-hover)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kyleledbetter** [comment]
Can you make it so the is optional by the admin template parameters and off by default?

**Comment by realityking** [comment]
Just beware, you should not check the template parameters from the normal mod_menu layout. You may not rely on a certain template being present.

**Comment by kyleledbetter** [comment]
ok maybe a menu module parameter then? I'd rather not have the option for hover at all...

**Comment by infograf768** [comment]
Many people are used to hover. If we could make it a parameter, that would be great.

**Comment by realrandal** [comment]
Oh, so it becomes real! Thanks Peter. 

Fixing menu and toolbar to top also should be optional with option to turn off this default way. Or NoNr will need create adminbar UNdocker ;)

**Comment by ghost** [comment]
New (better) pull request here:
https://github.com/Joomla3-Admin-template/joomla-cms/pull/103

**Pull request closed without merging**
